improvements
contributte/validator pull request #3
Opened 2021-02-12 17:47 UTC by petrparolek

- polished docs
- travis -> GitHub Actions
- updated ninjify/qa

2021-02-13 13:22 UTC, f3l1x commented
👍 by me. WDYT @jiripudil?

2021-02-14 11:09 UTC, jiripudil requested changes
I believe some of the links in readme are wrong. Apart from that, lgtm :+1:

2021-02-14 11:09 UTC, jiripudil commented on README.md
> +See [how to contribute](https://contributte.org) to this package. This package is currently maintained by these authors.
```suggestion
See [how to contribute](https://contributte.org/contributing.html) to this package. This package is currently maintained by these authors.
```

2021-02-14 11:09 UTC, jiripudil commented on README.md
> +Consider to [support](https://contributte.com/partners) **contributte** development team.
```suggestion
Consider to [support](https://contributte.org/partners.html) **contributte** development team.
```

2021-02-14 11:41 UTC, petrparolek commented on README.md
> +See [how to contribute](https://contributte.org) to this package. This package is currently maintained by these authors.
@f3l1x whick link is OK?

2021-02-14 11:41 UTC, petrparolek commented on README.md
> +Consider to [support](https://contributte.com/partners) **contributte** development team.
@f3l1x whick link is OK?

2021-02-14 11:43 UTC, petrparolek commented
I do not know which links are OK. I made readme by copy and paste from another contritutte packages.

2021-02-14 16:42 UTC, jiripudil commented
Oh, then I guess they're incorrect in other contributte packages 🤔 I've taken the suggested links from [contributte/bare](https://github.com/contributte/bare)

2021-02-15 20:55 UTC, f3l1x commented
Great catch @jiripudil. You're correct. Could you please @petrparolek update the links? And update these links in other packages as well, it should be easy change. Thank you.

2021-02-15 21:01 UTC, petrparolek commented
tjhhanks, update in this PR

2021-02-16 08:26 UTC, jiripudil commented
@petrparolek please check the links for typos like [this](https://github.com/contributte/validator/pull/3/commits/3713018da469fbc05fb95cddc582cc04a4219d99#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L51) before you update them in other repositories

2021-02-16 08:26 UTC, jiripudil approved these changes

2021-02-16 08:26 UTC, merged